import type { Metadata } from 'next';
import './globals.css';
import { Figtree } from 'next/font/google';

const roboto = Figtree({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'study time tracker',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
